# Generated by Django 6.0.3 on 2026-03-20 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customerfoodcategory'),
        ('donor', '0004_foodmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodRequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'rejected'), ('completed', 'completed')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('Customers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_user', to='customer.customer')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_food', to='donor.fooditemmodel')),
            ],
        ),
    ]
