# Generated by Django 6.0.3 on 2026-03-20 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_foodrequestmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodrequestmodel',
            old_name='Customers',
            new_name='user',
        ),
    ]
