# Generated by Django 6.0.3 on 2026-03-21 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_rename_customers_foodrequestmodel_user'),
        ('donor', '0009_fooddisplay_alter_fooddonormodel_food_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrequestmodel',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_food', to='donor.fooddonormodel'),
        ),
        migrations.AlterField(
            model_name='foodrequestmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_user', to='customer.customer'),
        ),
    ]
