# Generated by Django 6.0.3 on 2026-03-21 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_foodrequestmodel_food_and_more'),
        ('donor', '0009_fooddisplay_alter_fooddonormodel_food_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodrequestmodel',
            name='food_image',
            field=models.ImageField(blank=True, null=True, upload_to='request_images/'),
        ),
        migrations.AddField(
            model_name='foodrequestmodel',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodrequestmodel',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodrequestmodel',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_food_customer', to='donor.fooddonormodel'),
        ),
        migrations.AlterField(
            model_name='foodrequestmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_users', to='customer.customer'),
        ),
    ]
