# Generated by Django 6.0.3 on 2026-03-21 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_foodrequestmodel_food_image_foodrequestmodel_rating_and_more'),
        ('donor', '0009_fooddisplay_alter_fooddonormodel_food_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodrequestmodel',
            name='food_image',
        ),
        migrations.AddField(
            model_name='foodrequestmodel',
            name='food_images',
            field=models.ImageField(default='fooddonor_image/default.jpg', upload_to='fooddonor_image'),
        ),
        migrations.AlterField(
            model_name='foodrequestmodel',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_food_customers', to='donor.fooddonormodel'),
        ),
        migrations.AlterField(
            model_name='foodrequestmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_users_customer', to='customer.customer'),
        ),
    ]
