# Generated by Django 6.0.3 on 2026-03-22 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_remove_foodrequestmodel_food_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_imagescart', models.ImageField(default='fooddonor_image/default.jpg', upload_to='foodcustomer_image')),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('food_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_food', to='customer.foodrequestmodel')),
            ],
        ),
    ]
