# Generated by Django 6.0.3 on 2026-03-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_cartmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodrequestmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
