# Generated by Django 6.0.3 on 2026-03-26 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_cartmodel_price'),
        ('donor', '0009_fooddisplay_alter_fooddonormodel_food_images'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('pickedup', 'Pickedup'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('is_paid', models.BooleanField(default=False)),
                ('razer_pay_order_id', models.CharField(max_length=100, null=True)),
                ('total_quantity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to=settings.AUTH_USER_MODEL)),
                ('food_order', models.ManyToManyField(related_name='enrolled', to='donor.fooddonormodel')),
            ],
        ),
    ]
