# Generated by Django 6.0.3 on 2026-04-02 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_orderitem'),
        ('donor', '0011_alter_fooddonormodel_expairy_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='food_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_food', to='donor.fooddonormodel'),
        ),
    ]
