# Generated by Django 6.0.3 on 2026-04-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_alter_cartmodel_food_cart'),
        ('donor', '0011_alter_fooddonormodel_expairy_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='food_order',
            field=models.ManyToManyField(related_name='enrolleds_order', to='donor.fooddonormodel'),
        ),
    ]
