# Generated by Django 6.0.3 on 2026-04-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_alter_order_food_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='review',
            field=models.CharField(default=0),
            preserve_default=False,
        ),
    ]
