# Generated by Django 6.0.3 on 2026-04-28 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_review'),
        ('donor', '0012_donorprofile_latitude_donorprofile_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='donor.fooddonormodel'),
        ),
    ]
