# Generated by Django 6.0.3 on 2026-03-19 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_foodcategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_title', models.CharField(max_length=100)),
                ('food_description', models.CharField(max_length=300)),
                ('food_images', models.ImageField(default='course_images/defualt.png', null=True, upload_to='fooditem_image')),
                ('quantity', models.IntegerField()),
                ('is_free', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expairy_time', models.DateTimeField(auto_now=True)),
                ('available', models.BooleanField(default=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_item', to=settings.AUTH_USER_MODEL)),
                ('food_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donor.foodcategory')),
                ('organization_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizer', to='donor.donorprofile')),
            ],
        ),
    ]
