# Generated by Django 6.0.3 on 2026-03-20 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0005_alter_foodmodel_food_images_fooddonormodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddonormodel',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_donor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fooddonormodel',
            name='food_images',
            field=models.ImageField(default='fooditem_image', null=True, upload_to='fooditem_image'),
        ),
    ]
