# Generated by Django 6.0.3 on 2026-03-20 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0006_alter_fooddonormodel_donor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddonormodel',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_donors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fooddonormodel',
            name='food_images',
            field=models.ImageField(default='fooddonor_image/default.png', upload_to='fooddonor_image'),
        ),
    ]
