# Generated by Django 6.0.3 on 2026-03-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0008_alter_fooddonormodel_donor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fooddisplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=100)),
                ('image', models.ImageField(default='food_images1/default.jpg', null=True, upload_to='Food_donor')),
            ],
        ),
        migrations.AlterField(
            model_name='fooddonormodel',
            name='food_images',
            field=models.ImageField(default='fooddonor_image/default.jpg', upload_to='fooddonor_image'),
        ),
    ]
