# Generated by Django 6.0.3 on 2026-03-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0009_fooddisplay_alter_fooddonormodel_food_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddonormodel',
            name='status',
            field=models.CharField(default='Available', max_length=20),
        ),
    ]
