# Generated by Django 6.0.3 on 2026-03-31 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0010_fooddonormodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddonormodel',
            name='expairy_time',
            field=models.DateTimeField(),
        ),
    ]
