# Generated by Django 6.0.3 on 2026-08-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('', 'Choose Your Role'), ('donor', 'Donor'), ('customer', 'Customer')], max_length=20),
        ),
    ]
